
import os
import sys
import asyncio
from dotenv import load_dotenv

# Load env vars
load_dotenv()

# We assume PYTHONPATH is set correctly by the runner to include src and parent src
# But we can try to patch it just in case for a2a_mcp if it's missing
# (The user will run this with the correct PYTHONPATH ideally)

try:
    from ai_ppt.agents.orchestrator import OrchestratorAgent
except ImportError as e:
    print(f"Error importing OrchestratorAgent: {e}")
    print("Please run with PYTHONPATH set to include 'src' and the 'a2a_mcp' package source.")
    sys.exit(1)

async def prove_thinking():
    print("Initializing Orchestrator Agent (connecting to Gemini LLM)...")
    try:
        agent = OrchestratorAgent()
    except Exception as e:
        print(f"Failed to initialize agent: {e}")
        print("Check if GOOGLE_API_KEY is set in .env")
        return

    print("\n" + "="*60)
    print("🧪 PROOF OF DYNAMIC THOUGHT 🧪")
    print("The agent will now receive different goals and dynamically")
    print("generate search queries using its LLM brain.")
    print("="*60 + "\n")
    
    scenarios = [
        "I need to create a structured outline for a presentation about AI Agents.",
        "I need to generate a photorealistic image of a futuristic city.",
        "I need to write a funny speech script for the second slide."
    ]

    for i, goal in enumerate(scenarios, 1):
        print(f"Scenario {i}:")
        print(f"  🎯 Goal Input: \"{goal}\"")
        print("  🧠 Orchestrator is thinking...")
        
        # Call the decision method
        # This calls the real LLM configured in the agent
        search_query = await agent._decide_agent_search_query(goal)
        
        print(f"  💡 Decided Search Query: \"{search_query}\"")
        
        # Verify it's not the input goal itself (unless fallback happened)
        if search_query == goal:
            print("  ⚠️  (Fallback triggered or LLM returned same text)")
        else:
            print("  ✅  (Generated by LLM)")
            
        print("-" * 50)

if __name__ == "__main__":
    asyncio.run(prove_thinking())
